version: "3"
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
